[plugin]
repository = "https://github.com/Era-FFXIV/QuestShare.Plugin.git"
owners = ["nathanctech"]
project_path = "QuestShare.Plugin"
commit = "527c8004f6ca54d9b3721b7dffe3ed969269f26a"
version = "1.0.3.0"
